function [ epi ] = SLParseES( evs )
%SLPARSEES Parse EventSeries generated by StiLib(http://stilib.codeplex.com)
%   Detailed explanation goes here
import Analysis.Base.StiLib.*
es = evs.Times();
%%%%%%% Check StiLib backward compatbility, see Analysis2 for details %%%%%%
% backward compatbility number system digit
bnd = 4;
% keywords group separator maximum position
ksp = 10;
% keywords group
kg = es(2:ksp*bnd+1)-es(1:ksp*bnd);
% backward number system is 16
if max(kg)/min(kg) > 3
    epi = SLParseES16(es);
else
    epi = SLParseES2(es);
end
if ~isempty(epi.error)
    epi=[];
end

end

