function [ pes ] = SLParseES( evs )
%SLPARSEES Parse EventSeries generated by StiLib(http://stilib.codeplex.com)
%   Detailed explanation goes here
import Analysis.Core.* Analysis.Core.Stilib.*

end

