function Hd = CombNotch(fs,coef)
%COMBNOTCH Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.8 and the Signal Processing Toolbox 6.11.
%
% Generated on: 04-Sep-2009 21:32:00
%

% IIR Comb Notching filter designed using the IIRCOMB function.


Fn = str2double(coef{1});
Bw = str2double(coef{2});


% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N     = floor(fs/Fn);  % Order
BW    = Bw;   % Bandwidth
Apass = 1;   % Bandwidth Attenuation

[b, a] = iircomb(N, BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

end % [EOF]
