function Hd = Kaiser(fs,coef)
%KAISER Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 21-May-2008 23:17:00
%

% FIR Window Bandpass filter designed using the FIR1 function.


Fp1 = str2double(coef{1});
Fp2 = str2double(coef{2});


% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

Fstop1 = Fp1-1;              % First Stopband Frequency
Fpass1 = Fp1;              % First Passband Frequency
Fpass2 = Fp2;             % Second Passband Frequency
Fstop2 = Fp2+1;             % Second Stopband Frequency
Dstop1 = 0.001;             % First Stopband Attenuation
Dpass  = 0.00057564620966;  % Passband Ripple
Dstop2 = 0.001;             % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

end % [EOF]
