function Hd = Notch(fs,coef)
%Notch Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 04-Jul-2008 22:44:33
%

% IIR Notching filter designed using the IIRNOTCH function.


Fn = str2double(coef{1});
Bw = str2double(coef{2});


% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

Fnotch = Fn;  % Notch Frequency
BW     = Bw;   % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

end % [EOF]
